name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 
      - uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
        with:
          ruby-version: 2.6
    
      - name: Instalando dependências
        run: bundle install
      
      - name: rodando db
        run: rake db:create && rake db:migrate
      
      - name: Rodando servidor
        run: rails server
    
      - name: Rodando client
        run: yarn install && yarn dev
