version: "3.3"

services:
  client:
    container_name: client
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app

  api:
    container_name: api
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=localhost
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password