name: Continuos Integration
on: [push, pull_request]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_DB: 127.0.0.1
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Runner download
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.7
    
      - name: Install dependencies
        run: bundle install
      
      - name: Run database
        env:
          POSTGRES_DB: 127.0.0.1
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        run: rake db:create && rake db:migrate
      
      # - name: Run server
      #   run: rails server
      
      - name: Execute tests on api
        run: bundle exec rails test
  
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Runner download
        uses: actions/checkout@v2
      - name: Set up Node 
        uses: actions/setup-node@v1
        with:
          node-version: 14
    
      - name: Install dependencies
        run: yarn install
      
      # - name: Execute server
      #   run: yarn dev
      
      - name: Execute tests on client
        run: yarn run test:unit